const apiService = {
  clientregister: "users/users/clientsignup",
  advacateregister: "users/users/advacatesignup",
  clientsignin: "users/users/clientsignin",
  googleSign: "users/users/googleSign",
  getAIresponse: "users/users/getAIresponse",
  advacatesignin: "users/users/advacatesignin",
  emailVerify: "users/users/emailVerify",
  documentDownloader: "users/users/documentDownloader",
  createTemplateAdv: "advocate/advocate/createTemplateAdv",
  getAllAdvocates: "advocate/advocate/getAllAdvocates",
  getRssfeedcontent: "advocate/advocate/getRssfeedcontent",
  getAdvProfile: "advocate/advocate/getAdvProfile",
  updateProfile: "advocate/advocate/updateProfile",
  getAdvProfileID: "advocate/advocate/getAdvProfileID",
  request: "advocate/advocate/request",
  getRequest: "advocate/advocate/getRequest",
  getConnections: "advocate/advocate/getConnections",
  advocateAction: "advocate/advocate/advocateAction",
  templateDetails: "advocate/advocate/templateDetails",
  getTemplateID: "advocate/advocate/getTemplateIDItem",
  addToCartS: "advocate/advocate/addToCartS",
  getCartDetails: "advocate/advocate/getCartDetails",
  removCartDetails: "advocate/advocate/removCartDetails",
  checkoutCart: "advocate/advocate/checkoutCart",
  getClientInfo: "advocate/advocate/getClientInfo",
  getMyDocuments: "advocate/advocate/getMyDocuments",
  getCLientProfile: "advocate/advocate/getCLientProfile",
  updateClientProfile: "advocate/advocate/updateClientProfile",
  ForgotPassword: "users/users/ForgotPassword",
  resetpassword: "users/users/resetpassword",
  updateTemplate: "advocate/advocate/updateTemplate",
  getMyCreateDocs: "advocate/advocate/getMyCreateDocs",
  getcountryDocuments: "advocate/advocate/getcountryDocuments",
  searching: "advocate/advocate/searching",
  getTemplateIDEdit: "advocate/advocate/getTemplateIDEdit",
  updatedocx: "advocate/advocate/updatedocx",
  createDraft: "users/users/createDraft",
  getDraftlist: "users/users/getDraftlist",
  getsharelist: "users/users/getsharelist",
  getuploadlist: "users/users/getuploadlist",
  UploadFile: "users/users/UploadFile",
  transfer: "users/users/transfer",
  getadvocateList: "users/users/getadvocateList",
  ShareFile: "users/users/ShareFile",
  editSavedraft: "users/users/editSavedraft",
  getChooseDraft: "users/users/getChooseDraft",
  deleteFile: "users/users/deleteFile",
  getAdmin : 'admin/admin/getAdmin',
  getUserDetails : 'admin/admin/getUserDetails',
  getcontacts : 'admin/admin/getcontacts',
  addblogdetails : 'admin/admin/addblogdetails',
  getblogdetails : 'admin/admin/getblogdetails',
  getblogdetail : 'admin/admin/getblogdetail',
  changeStatus : 'admin/admin/changeStatus',


};
export default apiService;
